insert into DE1M.KISL_DWH_FACT_TRANSACTIONS
    (TRANS_ID, TRANS_DATE, CARD_NUM, OPER_TYPE, AMT, OPER_RESULT, TERMINAL)
select TRANS_ID, TRANS_DATE, CARD_NUM, OPER_TYPE, AMT, OPER_RESULT, TERMINAL
from DE1M.KISL_STG_TRAN